export const IPC_CHANNELS = {
  sourcesList: 'sources:list',
  sourcesChooseDirectory: 'sources:choose-directory',
  sourcesCreate: 'sources:create',
  sourcesUpdate: 'sources:update',
  sourcesRemove: 'sources:remove',
  filmsPage: 'films:page',
  filmsDetail: 'films:detail',
  filmsUpdate: 'films:update',
  filmsOpen: 'films:open',
  filmsShowInFolder: 'films:show-in-folder',
  filmsImportNfo: 'films:import-nfo',
  filmsRescan: 'films:rescan',
  tagsList: 'tags:list',
  scanStart: 'scan:start',
  scanCancel: 'scan:cancel',
  scanStatus: 'scan:status',
  scanProgress: 'scan:progress',
  appInfo: 'app:info',
  appHealth: 'app:health',
  appOpenDataFolder: 'app:open-data-folder',
  appOpenLogsFolder: 'app:open-logs-folder',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  settingsTestFfprobe: 'settings:test-ffprobe',
} as const;
